version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.4

jobs:
  build:
    docker:
      - image: cimg/node:20.7-browsers
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm install --global npm@latest
      - run: npm install
      - run:
          command: |
            google-chrome --version
          name: Check install
      - run: npm test



# version: 2
# # orbs:
# #   browser-tools: circleci/browser-tools@1.1.0
# jobs:
#   build:
#     docker:
#       - image: cimg/node:20.8.0-browsers
#         environment:
#           CHROME_BIN: "/usr/bin/google-chrome"
#     steps:
#       - circleci/browser-tools@1.1.0/install-browser-tools
#       - checkout
#       - run: npm install --global npm@latest
#       - run: npm install
#       - run: |
#           node --version
#           java --version
#           google-chrome --version
#       - run: npm test
# orbs:
#   browser-tools: circleci/browser-tools@1.1.0
# jobs:
#   build:
#     docker:
#       - image: cimg/node:15.0.1-browsers
#     steps:
#       - browser-tools/install-browser-tools
#       - checkout
#       - run: |
#           node --version
#           java --version
#           google-chrome --version
